a= input()
b= input()

try:
    print("The sum of a & b is",int (a)+int(b))
except Exception as f:
    print(f)

    print("Hello this is the work of try handling")
